# Generated by Django 4.0.1 on 2022-03-24 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='names',
            unique_together=set(),
        ),
    ]
